// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2_BTkd3V5AvWSrhFNrxXhGn_Wf9qWOjM',
    appId: '1:949309418294:web:eb98936c4031fce2002197',
    messagingSenderId: '949309418294',
    projectId: 'the-bed-is-my-stage',
    authDomain: 'the-bed-is-my-stage.firebaseapp.com',
    storageBucket: 'the-bed-is-my-stage.appspot.com',
    measurementId: 'G-LY4Q32J0PX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHWnjAvjBy1O4IgoQWzAfk4aeBZvtva8Y',
    appId: '1:949309418294:android:6c2549bf3320dcb0002197',
    messagingSenderId: '949309418294',
    projectId: 'the-bed-is-my-stage',
    storageBucket: 'the-bed-is-my-stage.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK0MlQWLuUn9PhsU3wto58f9ROo3w-kKs',
    appId: '1:949309418294:ios:87a81a69be58a367002197',
    messagingSenderId: '949309418294',
    projectId: 'the-bed-is-my-stage',
    storageBucket: 'the-bed-is-my-stage.appspot.com',
    iosBundleId: 'com.example.first',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK0MlQWLuUn9PhsU3wto58f9ROo3w-kKs',
    appId: '1:949309418294:ios:87a81a69be58a367002197',
    messagingSenderId: '949309418294',
    projectId: 'the-bed-is-my-stage',
    storageBucket: 'the-bed-is-my-stage.appspot.com',
    iosBundleId: 'com.example.first',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2_BTkd3V5AvWSrhFNrxXhGn_Wf9qWOjM',
    appId: '1:949309418294:web:c42700b2b6020fe4002197',
    messagingSenderId: '949309418294',
    projectId: 'the-bed-is-my-stage',
    authDomain: 'the-bed-is-my-stage.firebaseapp.com',
    storageBucket: 'the-bed-is-my-stage.appspot.com',
    measurementId: 'G-7L4SD15LKD',
  );
}
